name: Update GitHub Profile

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight
  workflow_dispatch:  # Allows for manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Update Script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python scripts/update_profile.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "kaurpahujasirjan@gmail.com"
          git config --local user.name "Sirjan Kaur Pahuja"
          
          # Fetch the latest changes from the remote repository
          git fetch origin

          # Rebase local changes on top of the latest from the remote
          git rebase origin/main

          # Add changes and commit
          git add activity.md
          git commit -m "Update daily activity"
          
          # Push changes (force push if necessary to avoid conflicts)
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/sirjan255/github-profile-automation.git main --force
