name: Update GitHub Profile

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight
  workflow_dispatch:  # Allows for manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: python -m pip install --upgrade pip requests

      - name: Run Update Script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python scripts/update_profile.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "kaurpahujasirjan@gmail.com"
          git config --local user.name "Sirjan Kaur Pahuja"

          # Pull the latest changes from the remote repository
          git pull origin main

          # Check if activity.md exists before adding
          if [ -f activity.md ]; then
            git add activity.md
            git commit -m "Update daily activity" || echo "No changes to commit"
          else
            echo "activity.md does not exist, skipping commit."
          fi

          # Push changes
          git push
